[target.thumbv6m-none-eabi]
# probe-rs chip list | grep -i PY32
runner = "probe-rs run --chip PY32F072xB"

# rustflags = [
#   "-C", "linker=flip-link",
# ]

[build]
target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "info"